package Spring.model;
// Generated Dec 22, 2018 7:52:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Measurement generated by hbm2java
 */
@Entity
@Table(name = "measurement", schema = "dbo", catalog = "spaCCH")
public class Measurement implements java.io.Serializable {

	private MeasurementId id;
	private Double bmi;
	private Double bodymass;
	private Double fatcontent;
	private Double height;
	private Double musclecontent;
	private Integer status;
	private Double weight;
	private Integer deleted;
	private Date createdate;
	private Date updatedate;
	private Long recordversion;

	public Measurement() {
	}

	public Measurement(MeasurementId id) {
		this.id = id;
	}

	public Measurement(MeasurementId id, Double bmi, Double bodymass, Double fatcontent, Double height,
			Double musclecontent, Integer status, Double weight, Integer deleted, Date createdate, Date updatedate,
			Long recordversion) {
		this.id = id;
		this.bmi = bmi;
		this.bodymass = bodymass;
		this.fatcontent = fatcontent;
		this.height = height;
		this.musclecontent = musclecontent;
		this.status = status;
		this.weight = weight;
		this.deleted = deleted;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.recordversion = recordversion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "appointment", column = @Column(name = "appointment", nullable = false)),
			@AttributeOverride(name = "service", column = @Column(name = "service", nullable = false)),
			@AttributeOverride(name = "time", column = @Column(name = "time", nullable = false)) })
	public MeasurementId getId() {
		return this.id;
	}

	public void setId(MeasurementId id) {
		this.id = id;
	}

	@Column(name = "bmi", precision = 53, scale = 0)
	public Double getBmi() {
		return this.bmi;
	}

	public void setBmi(Double bmi) {
		this.bmi = bmi;
	}

	@Column(name = "bodymass", precision = 53, scale = 0)
	public Double getBodymass() {
		return this.bodymass;
	}

	public void setBodymass(Double bodymass) {
		this.bodymass = bodymass;
	}

	@Column(name = "fatcontent", precision = 53, scale = 0)
	public Double getFatcontent() {
		return this.fatcontent;
	}

	public void setFatcontent(Double fatcontent) {
		this.fatcontent = fatcontent;
	}

	@Column(name = "height", precision = 53, scale = 0)
	public Double getHeight() {
		return this.height;
	}

	public void setHeight(Double height) {
		this.height = height;
	}

	@Column(name = "musclecontent", precision = 53, scale = 0)
	public Double getMusclecontent() {
		return this.musclecontent;
	}

	public void setMusclecontent(Double musclecontent) {
		this.musclecontent = musclecontent;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "weight", precision = 53, scale = 0)
	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	@Column(name = "deleted")
	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", length = 23)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedate", length = 23)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@Column(name = "recordversion", precision = 10, scale = 0)
	public Long getRecordversion() {
		return this.recordversion;
	}

	public void setRecordversion(Long recordversion) {
		this.recordversion = recordversion;
	}

}
