package Spring.model;
// Generated Dec 22, 2018 7:52:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MeasurementId generated by hbm2java
 */
@Embeddable
public class MeasurementId implements java.io.Serializable {

	private int appointment;
	private int service;
	private int time;

	public MeasurementId() {
	}

	public MeasurementId(int appointment, int service, int time) {
		this.appointment = appointment;
		this.service = service;
		this.time = time;
	}

	@Column(name = "appointment", nullable = false)
	public int getAppointment() {
		return this.appointment;
	}

	public void setAppointment(int appointment) {
		this.appointment = appointment;
	}

	@Column(name = "service", nullable = false)
	public int getService() {
		return this.service;
	}

	public void setService(int service) {
		this.service = service;
	}

	@Column(name = "time", nullable = false)
	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MeasurementId))
			return false;
		MeasurementId castOther = (MeasurementId) other;

		return (this.getAppointment() == castOther.getAppointment()) && (this.getService() == castOther.getService())
				&& (this.getTime() == castOther.getTime());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAppointment();
		result = 37 * result + this.getService();
		result = 37 * result + this.getTime();
		return result;
	}

}
