package Spring.model;
// Generated Dec 22, 2018 7:52:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reviewstaff generated by hbm2java
 */
@Entity
@Table(name = "reviewstaff", schema = "dbo", catalog = "spaCCH")
public class Reviewstaff implements java.io.Serializable {

	private Integer id;
	private String content;
	private Date date;
	private Integer star;
	private int staff;
	private int customer;
	private Integer deleted;
	private Date createdate;
	private Date updatedate;
	private Long recordversion;

	public Reviewstaff() {
	}

	public Reviewstaff(String content, int staff, int customer) {
		this.content = content;
		this.staff = staff;
		this.customer = customer;
	}

	public Reviewstaff(String content, Date date, Integer star, int staff, int customer, Integer deleted,
			Date createdate, Date updatedate, Long recordversion) {
		this.content = content;
		this.date = date;
		this.star = star;
		this.staff = staff;
		this.customer = customer;
		this.deleted = deleted;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.recordversion = recordversion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 23)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "star")
	public Integer getStar() {
		return this.star;
	}

	public void setStar(Integer star) {
		this.star = star;
	}

	@Column(name = "staff", nullable = false)
	public int getStaff() {
		return this.staff;
	}

	public void setStaff(int staff) {
		this.staff = staff;
	}

	@Column(name = "customer", nullable = false)
	public int getCustomer() {
		return this.customer;
	}

	public void setCustomer(int customer) {
		this.customer = customer;
	}

	@Column(name = "deleted")
	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", length = 23)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedate", length = 23)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@Column(name = "recordversion", precision = 10, scale = 0)
	public Long getRecordversion() {
		return this.recordversion;
	}

	public void setRecordversion(Long recordversion) {
		this.recordversion = recordversion;
	}

}
