package Spring.model;
// Generated Dec 22, 2018 7:52:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServiceBedId generated by hbm2java
 */
@Embeddable
public class ServiceBedId implements java.io.Serializable {

	private int bed;
	private int service;

	public ServiceBedId() {
	}

	public ServiceBedId(int bed, int service) {
		this.bed = bed;
		this.service = service;
	}

	@Column(name = "bed", nullable = false)
	public int getBed() {
		return this.bed;
	}

	public void setBed(int bed) {
		this.bed = bed;
	}

	@Column(name = "service", nullable = false)
	public int getService() {
		return this.service;
	}

	public void setService(int service) {
		this.service = service;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServiceBedId))
			return false;
		ServiceBedId castOther = (ServiceBedId) other;

		return (this.getBed() == castOther.getBed()) && (this.getService() == castOther.getService());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBed();
		result = 37 * result + this.getService();
		return result;
	}

}
